# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f69a5307b4737436b0ada4dd4fc7245"
name = "Chatbot Feature Dev MCP"
handle = "chatbot-feature-dev-mcp"
application_url = "https://52fe-103-187-96-186.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = ["https://52fe-103-187-96-186.ngrok-free.app/auth/callback", "https://52fe-103-187-96-186.ngrok-free.app/auth/shopify/callback", "https://52fe-103-187-96-186.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
